services:
  app:
    build: .
    image: store-assistant:latest
    container_name: store-assistant-${CLIENT_ID}
    restart: unless-stopped
    env_file: ../volumes/data/${CLIENT_ID}/.env
    volumes:
      - '../StoreAssistant_volumes/data:/app/app/_data'
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      # HTTPS router
      - "traefik.http.routers.store-assistant-${CLIENT_ID}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.store-assistant-${CLIENT_ID}.entrypoints=websecure"
      - "traefik.http.routers.store-assistant-${CLIENT_ID}.tls.certresolver=letsencrypt"
      - "traefik.http.services.store-assistant-${CLIENT_ID}.loadbalancer.server.port=${PORT}"
      # HTTP -> HTTPS redirect
      - "traefik.http.routers.store-assistant-${CLIENT_ID}-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.store-assistant-${CLIENT_ID}-http.entrypoints=web"
      - "traefik.http.routers.store-assistant-${CLIENT_ID}-http.middlewares=store-assistant-${CLIENT_ID}-https-redirect"
      - "traefik.http.middlewares.store-assistant-${CLIENT_ID}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.store-assistant-${CLIENT_ID}-https-redirect.redirectscheme.permanent=true"

networks:
  traefik-public:
    external: true
