name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to SSH_HOST_REGRU
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST_REGRU }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/StoreAssistant
            ./update.sh --all

      # - name: Deploy to SSH_HOST_2
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: ${{ secrets.SSH_HOST_2 }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd ~/StoreAssistant
      #       ./update.sh --all
